"""empty message

Revision ID: 9a6def6185e2
Revises: 6ca58d9fd481
Create Date: 2023-03-19 02:31:15.647894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6def6185e2'
down_revision = '6ca58d9fd481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_created_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_column('guest_created_date')

    # ### end Alembic commands ###
