"""empty message

Revision ID: 9180d876bf04
Revises: 4bfecf0a1b25
Create Date: 2023-03-17 20:58:19.653845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9180d876bf04'
down_revision = '4bfecf0a1b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_transaction_deleted', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('guest_transaction_description')

    with op.batch_alter_table('rate_schedules', schema=None) as batch_op:
        batch_op.alter_column('rate_start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('rate_discount',
               existing_type=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('rate_premium',
               existing_type=sa.NUMERIC(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rate_schedules', schema=None) as batch_op:
        batch_op.alter_column('rate_premium',
               existing_type=sa.NUMERIC(),
               nullable=False)
        batch_op.alter_column('rate_discount',
               existing_type=sa.NUMERIC(),
               nullable=False)
        batch_op.alter_column('rate_start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    with op.batch_alter_table('guest_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_transaction_description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('guest_transaction_deleted')

    # ### end Alembic commands ###
