"""empty message

Revision ID: 6cf54f1d1557
Revises: e55ad7b6f24e
Create Date: 2023-03-19 03:11:10.988635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf54f1d1557'
down_revision = 'e55ad7b6f24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stay_last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stays', schema=None) as batch_op:
        batch_op.drop_column('stay_last_updated')

    # ### end Alembic commands ###
