"""empty message

Revision ID: 48a70b1a4061
Revises: 9180d876bf04
Create Date: 2023-03-17 21:09:37.632189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a70b1a4061'
down_revision = '9180d876bf04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_transaction_description', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_transactions', schema=None) as batch_op:
        batch_op.drop_column('guest_transaction_description')

    # ### end Alembic commands ###
