"""empty message

Revision ID: 5bd9a893a14e
Revises: 6cf54f1d1557
Create Date: 2023-03-19 03:51:32.518955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd9a893a14e'
down_revision = '6cf54f1d1557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_index('guests_first_names')

    with op.batch_alter_table('stays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stay_created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stays', schema=None) as batch_op:
        batch_op.drop_column('stay_created_date')

    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.create_index('guests_first_names', ['guest_first_name'], unique=False)

    # ### end Alembic commands ###
