"""empty message

Revision ID: e55ad7b6f24e
Revises: 9a6def6185e2
Create Date: 2023-03-19 03:00:02.986178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55ad7b6f24e'
down_revision = '9a6def6185e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_column('guest_last_updated')

    # ### end Alembic commands ###
