"""empty message

Revision ID: 4bfecf0a1b25
Revises: 
Create Date: 2023-03-12 22:38:41.819713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfecf0a1b25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('amenity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amenity_description', sa.Text(), nullable=False),
    sa.Column('amenity_premium', sa.Numeric(), nullable=False),
    sa.Column('amenity_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amenity_deleted_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('amenity_id')
    )
    op.create_table('guests',
    sa.Column('guest_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guest_first_name', sa.Text(), nullable=False),
    sa.Column('guest_middle_initial', sa.String(length=1), nullable=True),
    sa.Column('guest_last_name', sa.Text(), nullable=False),
    sa.Column('guest_phone_number', sa.Text(), nullable=False),
    sa.Column('guest_email', sa.Text(), nullable=True),
    sa.Column('guest_state', sa.String(length=2), nullable=True),
    sa.Column('guest_birthdate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('guest_id')
    )
    op.create_table('rate_schedules',
    sa.Column('rate_schedule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rate_start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rate_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_discount', sa.Numeric(), nullable=False),
    sa.Column('rate_premium', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('rate_schedule_id')
    )
    op.create_table('room_types',
    sa.Column('room_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_type_bed_type', sa.Text(), nullable=False),
    sa.Column('room_type_bed_count', sa.Integer(), nullable=False),
    sa.Column('room_type_max_occupants', sa.Integer(), nullable=False),
    sa.Column('room_type_base_rate', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('room_type_id'),
    sa.UniqueConstraint('room_type_bed_type')
    )
    op.create_table('transaction_types',
    sa.Column('transaction_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_type_description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('transaction_type_id')
    )
    op.create_table('guest_transactions',
    sa.Column('guest_transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_type_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('guest_transaction_charge', sa.Numeric(), nullable=False),
    sa.Column('guest_transaction_payment', sa.Numeric(), nullable=False),
    sa.Column('guest_transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('guest_transaction_description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], ),
    sa.ForeignKeyConstraint(['transaction_type_id'], ['transaction_types.transaction_type_id'], ),
    sa.PrimaryKeyConstraint('guest_transaction_id')
    )
    op.create_table('room_type_rates',
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('rate_schedule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rate_schedule_id'], ['rate_schedules.rate_schedule_id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.room_type_id'], ),
    sa.PrimaryKeyConstraint('room_type_id', 'rate_schedule_id')
    )
    op.create_table('rooms',
    sa.Column('room_number', sa.Text(), nullable=False),
    sa.Column('room_ready', sa.Boolean(), nullable=False),
    sa.Column('room_available', sa.DateTime(timezone=True), nullable=True),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('room_fits_crib', sa.Boolean(), nullable=False),
    sa.Column('room_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('room_deleted_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.room_type_id'], ),
    sa.PrimaryKeyConstraint('room_number')
    )
    op.create_table('rooms_amenities',
    sa.Column('room_number', sa.Text(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.amenity_id'], ),
    sa.ForeignKeyConstraint(['room_number'], ['rooms.room_number'], )
    )
    op.create_table('stays',
    sa.Column('stay_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_number', sa.Text(), nullable=False),
    sa.Column('stay_holder_guest_id', sa.Integer(), nullable=False),
    sa.Column('stay_check_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stay_actual_check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stay_check_out', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stay_actual_check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stay_occupant_count', sa.Integer(), nullable=False),
    sa.Column('stay_duration', sa.Integer(), nullable=False),
    sa.Column('stay_status', sa.Text(), nullable=False),
    sa.Column('stay_cancel_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_number'], ['rooms.room_number'], ),
    sa.PrimaryKeyConstraint('stay_id')
    )
    op.create_table('guests_stays',
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('stay_id', sa.Integer(), nullable=False),
    sa.Column('guest_stay_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.guest_id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['stays.stay_id'], ),
    sa.PrimaryKeyConstraint('guest_id', 'stay_id')
    )
    op.create_table('stay_balances',
    sa.Column('stay_balance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stay_total_charges', sa.Numeric(), nullable=False),
    sa.Column('stay_total_payments', sa.Numeric(), nullable=False),
    sa.Column('stay_balance', sa.Numeric(), nullable=False),
    sa.Column('stay_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stay_id'], ['stays.stay_id'], ),
    sa.PrimaryKeyConstraint('stay_balance_id')
    )
    op.create_table('transactions_to_balances',
    sa.Column('guest_transaction_id', sa.Integer(), nullable=False),
    sa.Column('stay_balance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guest_transaction_id'], ['guest_transactions.guest_transaction_id'], ),
    sa.ForeignKeyConstraint(['stay_balance_id'], ['stay_balances.stay_balance_id'], ),
    sa.PrimaryKeyConstraint('guest_transaction_id', 'stay_balance_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions_to_balances')
    op.drop_table('stay_balances')
    op.drop_table('guests_stays')
    op.drop_table('stays')
    op.drop_table('rooms_amenities')
    op.drop_table('rooms')
    op.drop_table('room_type_rates')
    op.drop_table('guest_transactions')
    op.drop_table('transaction_types')
    op.drop_table('room_types')
    op.drop_table('rate_schedules')
    op.drop_table('guests')
    op.drop_table('amenities')
    # ### end Alembic commands ###
